name: shaunfox.com
markdown: redcarpet
highlighter: pygments
site.name: shaunfox.com
permalink: /:categories/:title
url: http://localhost:4000
paginate_per_category: true

# Build settings
markdown: kramdown