name: shaunfox.com
site.name: shaunfox.com
permalink: /:categories/:title.html
url: http://localhost:4000
paginate_per_category: true
highlighter: rouge
gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown