name: shaunfox.com
title: shaunfox.com
permalink: /:categories/:title.html
url: http://shaunfox.com
paginate_per_category: true
highlighter: rouge
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown